# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lode < Formula
  desc "Fast, drop-in compatible reimplementation of DVC's data-versioning core, in Go"
  homepage "https://github.com/getlode/lode"
  version "0.1.2"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/getlode/lode/releases/download/v0.1.2/lode_0.1.2_darwin_amd64.tar.gz"
      sha256 "3aa7e05a459483930a4396f07685f5b341838e604d67aa323d3f36dccdbfe5e6"

      def install
        bin.install "lode"
      end
    end
    on_arm do
      url "https://github.com/getlode/lode/releases/download/v0.1.2/lode_0.1.2_darwin_arm64.tar.gz"
      sha256 "6b159eaa52c95614097902ab8c53f64f8226c0345eba85c934fb2f57d22247a7"

      def install
        bin.install "lode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.2/lode_0.1.2_linux_amd64.tar.gz"
        sha256 "ae4ea12c8c4090fe12f300d7dbde0639a3c77b020b8c8be69b9b5721557069f3"

        def install
          bin.install "lode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.2/lode_0.1.2_linux_arm64.tar.gz"
        sha256 "e86e32b6034c7d694a467f4e8dbd60ef7696fa77b9971553007b6c1971768cbf"

        def install
          bin.install "lode"
        end
      end
    end
  end

  test do
    system "#{bin}/lode", "--version"
  end
end
