# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lode < Formula
  desc "Fast DVC-compatible accelerator for add/status and S3-backed data sync, in Go"
  homepage "https://github.com/getlode/lode"
  version "0.1.3"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/getlode/lode/releases/download/v0.1.3/lode_0.1.3_darwin_amd64.tar.gz"
      sha256 "50da7a966bcd2120a805918ac3b03bb4a31cd773858534cd8a79d9cdc9a949bf"

      def install
        bin.install "lode"
      end
    end
    on_arm do
      url "https://github.com/getlode/lode/releases/download/v0.1.3/lode_0.1.3_darwin_arm64.tar.gz"
      sha256 "8959028ee382ecef790edba1e7ca95f26615a0e2db3e3afb63b5b62d84b3ae82"

      def install
        bin.install "lode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.3/lode_0.1.3_linux_amd64.tar.gz"
        sha256 "01a2e11a1d74b7114523c667837c5dcdf86bd3ec55d9cbbe964541ec6585af11"

        def install
          bin.install "lode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.3/lode_0.1.3_linux_arm64.tar.gz"
        sha256 "800de1a32b300bb30b2714195c0f49614cf01b47f3348ecfea6814bd1624b2b2"

        def install
          bin.install "lode"
        end
      end
    end
  end

  test do
    system "#{bin}/lode", "--version"
  end
end
