# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lode < Formula
  desc "Fast, drop-in compatible reimplementation of DVC's data-versioning core, in Go"
  homepage "https://github.com/getlode/lode"
  version "0.1.1"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/getlode/lode/releases/download/v0.1.1/lode_0.1.1_darwin_amd64.tar.gz"
      sha256 "f4e22ebedbc6242dc60385bd0b3e0b02e663225cd403037399521ccc141019fa"

      def install
        bin.install "lode"
      end
    end
    on_arm do
      url "https://github.com/getlode/lode/releases/download/v0.1.1/lode_0.1.1_darwin_arm64.tar.gz"
      sha256 "76256a97304ad9ea484a50f6d306adc2fd11ce036301fb4102a5d0e1ba8c2128"

      def install
        bin.install "lode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.1/lode_0.1.1_linux_amd64.tar.gz"
        sha256 "97483c0ec9c79f3c12b7720eb79fba49bb5917c8a82705fa5538f776d28bdabe"

        def install
          bin.install "lode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlode/lode/releases/download/v0.1.1/lode_0.1.1_linux_arm64.tar.gz"
        sha256 "f75d35f2dc84421bb3e01387a587d6f530a815f44b7e0db45b93d58d546fc2e5"

        def install
          bin.install "lode"
        end
      end
    end
  end

  test do
    system "#{bin}/lode", "--version"
  end
end
